/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2024-03-27 11:52:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;

public final class patientData_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/meta.jsp", out, false);
      out.write("\n");
      out.write("    <title>Patient Data App</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<header>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h1 style=\"text-align: center;\"><span style=\"float: left;\">Patient Data App</span>Patient Data<span style=\"float: right;\">Jash Shah</span></h1>\n");
      out.write("        <div style=\"display: flex; flex-direction: row; justify-content: center;\">\n");
      out.write("            <form method=\"GET\" action=\"/index.jsp\" style=\"margin-left: 20px\">\n");
      out.write("                <button type=\"submit\" style=\" padding: 6px 10px; float: left;\">< Go to Homepage</button>\n");
      out.write("            </form>\n");
      out.write("            <form method=\"GET\" action=\"/patientList.html\" style=\"margin-left: 20px\">\n");
      out.write("                <button type=\"submit\" style=\" padding: 6px 10px; float: left;\">< Go to Patient List</button>\n");
      out.write("            </form>\n");
      out.write("            <form method=\"GET\" action=\"/oldest.jsp\" style=\"margin-left: 20px\">\n");
      out.write("                <button type=\"submit\" style=\" padding: 6px 10px; float: left;\">< Go to Oldest Patients</button>\n");
      out.write("            </form>\n");
      out.write("            <form method=\"GET\" action=\"/youngest.jsp\" style=\"margin-left: 20px\">\n");
      out.write("                <button type=\"submit\" style=\" padding: 6px 10px; float: left;\">< Go to Youngest Patients</button>\n");
      out.write("            </form>\n");
      out.write("            <form method=\"GET\" action=\"/runAlive.html\" style=\"margin-left: 20px\">\n");
      out.write("                <button type=\"submit\" style=\" padding: 6px 10px; float: left;\">< Go to Alive Patients</button>\n");
      out.write("            </form>\n");
      out.write("            <form method=\"GET\" action=\"/runDead.html\" style=\"margin-left: 20px\">\n");
      out.write("                <button type=\"submit\" style=\" padding: 6px 10px; float: left;\">< Go to Dead Patient</button>\n");
      out.write("            </form>\n");
      out.write("            <form method=\"GET\" action=\"/dateAfter.jsp\" style=\"margin-left: 20px\">\n");
      out.write("                <button type=\"submit\" style=\" padding: 6px 10px; float: left;\">< Go to Date After Filter</button>\n");
      out.write("            </form>\n");
      out.write("            <form method=\"GET\" action=\"/dateBefore.jsp\" style=\"margin-left: 20px\">\n");
      out.write("                <button type=\"submit\" style=\" padding: 6px 10px; float: left;\">< Go to Date Before Filter</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</header>\n");

    String href = "/runDeleteRecord.html/?patientId=" + ((String) request.getAttribute("id"));

      out.write("\n");
      out.write("<div style=\"display: flex; justify-content: right; margin-right: 20px;\">\n");
      out.write("    <button style=\"padding: 6px 10px; margin-top: 20px;\" onclick=\"window.location.href='");
      out.print(href);
      out.write("';\">Delete Record</button>\n");
      out.write("</div>\n");
      out.write("<div id=\"managerTable\">\n");
      out.write("    ");

        List<String> columnNames = (List<String>) request.getAttribute("columnNames");
    
      out.write("\n");
      out.write("    <table style=\"text-align: left; position: relative; margin-top: 250px;\">\n");
      out.write("        <tr>\n");
      out.write("            ");

                for(String columnName : columnNames)
                {
            
      out.write("\n");
      out.write("            <th>");
      out.print(columnName);
      out.write("</th>\n");
      out.write("            ");
}
      out.write("\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            ");

                for(String columnName : columnNames)
                {
                    String value = (String) request.getAttribute(columnName);
            
      out.write("\n");
      out.write("            <td style=\"border: 1px solid black; text-align: center; padding: 10px;\">");
      out.print( value );
      out.write("</td>\n");
      out.write("            ");
}
      out.write("\n");
      out.write("        </tr>\n");
      out.write("    </table>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
